### ISSUE TITLE
Jekyll vs hugo

### ISSUE THREAD

**Issue by luiscachog** [doxmx/doxmx.github.io#1]
Hi team, 

Just to start with something on this repo, I believe instead of use Jekyll, we can use [hugo](https://gohugo.io/) for the static webpage.
I recommended for a simple workflow, a straightforward usage and it is just a binary, instead of the bunch of ruby gems to get Jekyll working.
Also here is the integration guide with github pages. [https://gohugo.io/hosting-and-deployment/hosting-on-github/](https://gohugo.io/hosting-and-deployment/hosting-on-github/)

**Comment by tonyskapunk** [comment]
@k4ch0 thanks for sharing that info, I honestly wanted to look for something diff but since jekyll was the default I wanted to give it a try, but I've just heard good things about hugo that I'm all for doing the extra effort and test it.

**Comment by luiscachog** [comment]
Cool!

As hugo doesn't have a default theme, we need to choose between the available ones: [https://themes.gohugo.io/](https://themes.gohugo.io/)

My votes are for: 
![image](https://user-images.githubusercontent.com/1848897/48587033-4e1eaf00-e8f7-11e8-9672-a5432c60f984.png)
[https://themes.gohugo.io/kube/](https://themes.gohugo.io/kube/)


![image](https://user-images.githubusercontent.com/1848897/48587078-77d7d600-e8f7-11e8-8f32-613d14a97eb4.png)

[https://themes.gohugo.io/hugo-theme-learn/](https://themes.gohugo.io/hugo-theme-learn/)

Lets the team vote!!

**Comment by tonyskapunk** [comment]
I've been playing with it, and set `beautifulhugo` for testing https://github.com/doxmx/blog/blob/master/config.toml#L4, of course it can be anything else, to test yourself:
- Install hugo (https://gohugo.io/getting-started/installing/)
- Clone the repo:
  ```
  git clone https://github.com/doxmx/blog.git
  cd blog
  hugo server -D
  ```
- Open your browser in: http://localhost:1313/

Still bare bones but anyone interested is more than welcome to contribute.

**Comment by luiscachog** [comment]
I assume we are using hugo now, I'm closing this issue.
